---
experiment:
  name: tiger_detector_exp21
  folder: /home/cortwave/projects/tigerc/tiger_detection/detection_exp
phase: train
task: detect

train:
    ann_path: /home/cortwave/projects/tigerc/tiger_detection/tigers_data/pseudolabel.json
    img_path: /home/cortwave/projects/tigerc/tiger_detection/tigers_data/detection_img/trainval
    img_size: 224
    transform: strong
val:
    ann_path: /home/cortwave/projects/tigerc/tiger_detection/tigers_data/val.json
    img_path: /home/cortwave/projects/tigerc/tiger_detection/tigers_data/detection_img/trainval
    img_size: 224
    transform: weak

model:
    load_weights: False
    weights_path: /home/haribo/okupyn_exp/binary_fpn_lowaug/best.h5
    pretrain_weights: /home/cortwave/projects/tigerc/tiger_detection/tigers_code/mobilenet_v2.pth.tar
    num_classes: 2
    img_size: 224
    feature_maps: 6
    name: retina_net
    backbone: mobilenet
    encoder_depth: 50
    pretrained: True
    visual_thr: 0.25

    loss:
        name: multibox_loss
        localization_loss: l1_smooth_loss
        confidence_loss: cross_entropy_loss

optimizer:
  name: adam
  lr: 0.001

scheduler:
  name: plateau
  mode: max
  patience: 5
  factor: 0.5
  min_lr: 0.000001

batch_size: 256
num_epochs: 250
early_stopping: 15
